algoritmo "Exercicio39"
var
Contador: Inteiro

inicio
      Escreval ("              Contagem Decrescente               ")
      Escreval (" ")
      Contador <- 10
      
      Enquanto (Contador >= 3) faca
               Escreval (Contador)
               Contador <- Contador - 1
      FimEnquanto
      
      Escreval (" ")
      Escreval ("                    Terminado!                  ")

fimalgoritmo