algoritmo "Exercicio38"
var
   Contador: Inteiro

inicio
      Escreval ("                Conte do 6 ao 11               ")
      Escreval (" ")
      
      Contador <- 6
      Enquanto (Contador <= 11) faca
               Escreval (Contador)
               Contador <- Contador + 1

      FimEnquanto
      
      Escreval (" ")
      Escreval (" ---------- Terminei de Contar ------------ ")


fimalgoritmo