algoritmo "Exercicio41"
var
Contador: Inteiro

inicio
      Escreval ("               Contagem Decrescente 5 em 5.             ")
      Escreval (" ")
      
      Contador <- 100
      
      Enquanto (Contador >=0) faca
               Escreval (Contador)
               Contador <- Contador - 5
      
      FimEnquanto
      
      Escreval (" ")
      Escreval ("                   Finalizado!                 ")

fimalgoritmo