algoritmo "Exercicio40"
var
Contador: Inteiro

inicio
      Escreval ("            Vamos contar de 3 em 3?            ")
      Escreval (" ")
      
      Contador <- 0
      
      Enquanto (Contador <= 18) faca
               Escreval (Contador)
               Contador <- Contador + 3
      
      FimEnquanto
      
      Escreval (" ")
      Escreval ("                 Terminado!                 ")

fimalgoritmo