algoritmo "Exercicio88"
var nome:caractere
i: inteiro

procedimento gerador (nome: caractere)
inicio
        Escreval(" ")
        escreval("+-------=======------+")
        para i de 1 ate 4 faca
             escreval("  Aprendendo Portugol  ")
        fimpara
        escreval("+-------=======------+")
        
fimprocedimento
inicio
      escreval("------------ PROCEDIMENTOS ------------")
      gerador ("Aprendendo Portugol 4x")

fimalgoritmo