algoritmo "Exercicio66"
var
   num,cont, resp:inteiro

inicio
      escreval("------------ Repetição com PARA ------------")
      escreval (" ")
      
      escreva("Informe numero 1 a 10 para uma tabuada simples: ")
      leia (num)
      escreval (" ")
      
      
      para cont <- 1 ate 10 faca
      resp <- num * cont
           escreval(num," x",cont," =",resp)

      fimpara

fimalgoritmo