algoritmo "Exercicio10"
var
   Lar1, Al1, Mt, Tinta: Real

inicio
      Escreva ("Informe a Largura do local a ser pintado: ")
      Leia (Lar1)
      Escreval (" ")
      Escreva ("Informe a Altura do local a ser pintado: ")
      Leia (Al1)
      Escreval (" ")
      
      Mt <- Lar1 * Al1
      Tinta <- Mt / 2
      
      Escreva ("Com ", Tinta, " Litros, eu consigo pintar", Mt, " metros.")
      Escreval (" ")
      
      
      

fimalgoritmo